# Generated by Django 3.0 on 2020-09-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0003_codes_filename_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='files',
        ),
        migrations.AddField(
            model_name='codes',
            name='content',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
